### ISSUE TITLE
Where to write [remoteMarkdownUrl](https://xxx.com/README.md)?

### ISSUE THREAD

**Issue by caijynb** [JerryC8080/docsify-remote-markdown#2]
in HTML body?in window.$docsify? or somewhere else?
My virtual machine don't have Mime type of markdown,So I install this plugin and write [remoteMarkdownUrl](https://xxx.com/README.md) in html body. But it doesn't work. Am i write in wrong place or just because virtual machine?

**Comment by JerryC8080** [comment]
You can only write `[remoteMarkdownUrl](https://xxx.com/README.md)]` at a markdown file.
See the [example](https://github.com/JerryC8080/docsify-remote-markdown/tree/master/example) at this repo.
