### ISSUE TITLE
CORS policy

### ISSUE THREAD

**Issue by a2ankitrai** [JerryC8080/docsify-remote-markdown#6]
I am trying the fetch another page and get below error in the console.

Access to fetch at * from origin * has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Any configuration to resolve the same?

**Comment by mg0324** [comment]
跨域了，引入github上的md文档是可以的。应该是github的raw的域名开放了跨域权限。
